### ISSUE TITLE
Start bit in motorola signals from Vector dbc files

### ISSUE THREAD

**Issue by laercio-barbosa** [reinzor/libcan-encode-decode#1]
Hi

I noted in Vector dbc files (opened as a txt file) the start bit field is the real start bit when signal is intel byte order, but is the 'end bit' when signal is motorola byte order. Have you seen this? How do you handle that (because storeSignal and extractSignal must receive both the real start bit position)?

Thanks

Laercio

**Comment by laercio-barbosa** [comment]
I've found the way here

[setMsbStartbit](https://github.com/ebroecker/canmatrix/blob/master/canmatrix/canmatrix.py)

**Comment by ebroecker** [comment]
you are right, the dbc motorola start bit is a bit wired.
As this library is related to canmatrix, you can use canmatrix to get the right start bit.
I also wrote something about the start bit issue: https://github.com/ebroecker/canmatrix/wiki/signal-Byteorder

If you need some C implementation you can use this code: https://github.com/ebroecker/SocketCandecodeSignals/blob/master/datenbasis.c#L112-L122

eduard

**Comment by laercio-barbosa** [comment]
Thanks Eduard
