### ISSUE TITLE
datatype error

### ISSUE THREAD

**Issue by Prj1508** [reinzor/libcan-encode-decode#10]
Hi.

I am trying to use your inline decode function from your repo and I am getting error message as below. 

Foe the frame, I am sending data field from a struct called msg as below which is an uint8_t array of 8 members. The error is also attached below. Please let me know

Code

msg.data[0] = 0x53;
  msg.data[1] = 0x40;
  msg.data[2] = 0x40;
  msg.data[3] = 0x0;
  msg.data[4] = 0x0;
  msg.data[5] = 0x0;
  msg.data[6] = 0x10;
  msg.data[7] = 0xBD;

  msg.header.frame_id = "";  // "0" for no frame.
  msg.header.stamp = ros::Time::now();

uint8_t msg.data[8];

//encode(src_array, 3.0, 56, 3, false, false, 1.000000, 0);
float PhysValue = decode(msg.data, 2,11, false, false, 1.000000, 0); // 3.0

Error

home/jpm/catkin_ws/src/ros_canopen/socketcan_bridge/src/steering_pub_socketcan.cpp: In function ‘int main(int, char**)’:
/home/jpm/catkin_ws/src/ros_canopen/socketcan_bridge/src/steering_pub_socketcan.cpp:118:12: error: expected initializer before ‘.’ token
 uint8_t msg.data[8] = 0;
            ^
/home/jpm/catkin_ws/src/ros_canopen/socketcan_bridge/src/steering_pub_socketcan.cpp:121:67: error: cannot convert ‘can_msgs::Frame_<std::allocator<void> >::_data_type {aka boost::array<unsigned char, 8ul>}’ to ‘const uint8_t* {aka const unsigned char*}’ for argument ‘1’ to ‘float decode(const uint8_t*, uint16_t, uint16_t, bool, bool, float, float)’
 float PhysValue = decode(msg.data, 2,11, false, false, 1.000000, 0); // 3.0
                                                                   ^
ros_canopen/socketcan_bridge/CMakeFiles/talker.dir/build.make:62: recipe for target 'ros_canopen/socketcan_bridge/CMakeFiles/talker.dir/src/steering_pub_socketcan.cpp.o' failed
make[2]: *** [ros_canopen/socketcan_bridge/CMakeFiles/talker.dir/src/steering_pub_socketcan.cpp.o] Error 1
CMakeFiles/Makefile2:3705: recipe for target 'ros_canopen/socketcan_bridge/CMakeFiles/talker.dir/all' failed
make[1]: *** [ros_canopen/socketcan_bridge/CMakeFiles/talker.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Prj1508** [comment]
Sorry, the code is rather,
// Construct the data as per the technical documentation.. Goal is to change the sensor id
  msg.data[0] = 0x53;
  msg.data[1] = 0x40;
  msg.data[2] = 0x40;
  msg.data[3] = 0x0;
  msg.data[4] = 0x0;
  msg.data[5] = 0x0;
  msg.data[6] = 0x10;
  msg.data[7] = 0xBD;

  msg.header.frame_id = "";  // "0" for no frame.
  msg.header.stamp = ros::Time::now();

uint8_t msg1=msg.data[8];

//encode(src_array, 3.0, 56, 3, false, false, 1.000000, 0);
float PhysValue = decode(msg1, 2,11, false, false, 1.000000, 0); // 3.0

**Comment by reinzor** [comment]
as your compiler says:

```
boost::array<unsigned char, 8ul> !=  const unsigned char*
```

If I can remember correctly, you can get access to the raw data in a `boost::array` by accessing `data()` but please see the boost docs for that. This is not an issue of this library.
