### ISSUE TITLE
encoding into more than 8 bits

### ISSUE THREAD

**Issue by Prj1508** [reinzor/libcan-encode-decode#11]
I would like to encode a value into 11 bits in a CAN frame. It seems like there is an overflow condition or something similar that is happening and I am not able to stuff these into required bits. Is there a limitation of this repo that would prevent me from encoding to more than 8 bits?

**Comment by reinzor** [comment]
Hi, the library should definitely work for values over 8 bits, look at the tests. What case is not working for you? Could you provide an example?

**Comment by reinzor** [comment]
Can I mark this issue al resolved?
