### ISSUE TITLE
Encode does not properly deal with sign extension

### ISSUE THREAD

**Issue by reinzor** [reinzor/libcan-encode-decode#5]
@ebroecker @laercio-barbosa 

It appears that the sign extension is not properly handled yet. I added a test that currently fails. I would like to have some help with this :). 

Thanks!

**Comment by reinzor** [comment]
I did some updates and added extra tests; fixed a problem with sign extensions, multibytes and end byte calculation. All tests seem to pass now. A second eye is always welcome :)

**Comment by ebroecker** [comment]
Seems you deleted the sign extension for storeSignal.
I think this is correct. I already thought that we don't need it here, but I wanted to check by example first. Didn't do this till now...

**Comment by reinzor** [comment]
@ebroecker , yes, I indeed deleted the addition of @laercio-barbosa ; I did not know what this was doing there. There was still a bug for multiple bytes in the storeSignal function, this is wat caused the problem; hopefully this is fixed now. Would be great if you could verify the functionality.

**Comment by reinzor** [comment]
I think this is fixed, will close the issue for now
