### ISSUE TITLE
storeSignal does not clear out stale bits

### ISSUE THREAD

**Issue by brentsink** [reinzor/libcan-encode-decode#7]
Hello,

Thank you for this wonderful library!  One thing I've noticed is that when you call storeSignal, it does not clear out the old bits that were in the CAN frame.  Instead, it leaves them there so if the new value is smaller those bits get overwritten, but the remaining bits (left-over from the last value that was there) are not changed.  Any suggestions on how to clear the entire range (i.e. from startbit 5 to a length of 16) out before storing a value?  Thanks!

**Comment by reinzor** [comment]
Thanks for the feedback. I usually start with zero Can frames but I guess it makes sense to indeed set the unused bits to zero. Will look into this.

**Comment by reinzor** [comment]
@brentsink , could you provide an example so we can test?

**Comment by brentsink** [comment]
Hi @reinzor , here is an example:

```
    int number = 11465;
    encode(frame.data, number, 16, 16, false, false, 0.5, 0);
    qDebug() << "original:" << number << ", decoded:" << decode(frame.data, 16, 16, false, false, 0.5, 0);

    // original: 11465 , decoded: 11465

    number = 11768;
    encode(frame.data, number, 16, 16, false, false, 0.5, 0);
    qDebug() << "original:" << number << ", decoded:" << decode(frame.data, 16, 16, false, false, 0.5, 0);

    // original: 11768 , decoded: 11769
```

The value inserted is always OR-ed with the value that is already in the frame.

**Comment by reinzor** [comment]
Thanks, added a PR, maybe not the nicest solution but seems to work. Could you test this @brentsink , @ebroecker , perhaps time for a review?

**Comment by brentsink** [comment]
I confirm that this solution works.  Thanks for fixing this!

**Comment by reinzor** [comment]
There were still some bugs in the clearing part. I added some extra tests to ensure the clearing does not mess with other stored parts.

**Comment by reinzor** [comment]
Changes are now in master
